# Mia's solution for chapter 1.9

In [3]:
from __future__ import print_function, division

import nsfg

In [6]:
preg = nsfg.ReadFemPreg()
preg.head()

caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  pregend1  \
0       1         1        NaN        NaN       NaN       NaN       6.0   
1       1         2        NaN        NaN       NaN       NaN       6.0   
2       2         1        NaN        NaN       NaN       NaN       5.0   
3       2         2        NaN        NaN       NaN       NaN       6.0   
4       2         3        NaN        NaN       NaN       NaN       6.0   

   pregend2  nbrnaliv  multbrth  ...  laborfor_i  religion_i  metro_i  \
0       NaN       1.0       NaN  ...           0           0        0   
1       NaN       1.0       NaN  ...           0           0        0   
2       NaN       3.0       5.0  ...           0           0        0   
3       NaN       1.0       NaN  ...           0           0        0   
4       NaN       1.0       NaN  ...           0           0        0   

       basewgt  adj_mod_basewgt      finalwgt  secu_p  sest  cmintvw  \
0  3410.389399      3869.349602   6448.271112       2     9      NaN   
1  3410.389399      3869.349602   6448.271112       2     9      NaN   
2  7226.301740      8567.549110  12999.542264       2    12      NaN   
3  7226.301740      8567.549110  12999.542264       2    12      NaN   
4  7226.301740      8567.549110  12999.542264       2    12      NaN   

   totalwgt_lb  
0       8.8125  
1       7.8750  
2       9.1250  
3       7.0000  
4       6.1875  

[5 rows x 244 columns]

## Exercise 1.1

Q1: Select the birthord column, print the value counts, and compare to results published in the codebook.

In [7]:
preg.birthord.value_counts().sort_index()

1.0     4413
2.0     2874
3.0     1234
4.0      421
5.0      126
6.0       50
7.0       20
8.0        7
9.0        2
10.0       1
Name: birthord, dtype: int64

Q2: Select the prglngth column, print the value counts, and compare to results published in the codebook.

In [10]:
preg.prglngth.value_counts().sort_index()

0       15
1        9
2       78
3      151
4      412
5      181
6      543
7      175
8      409
9      594
10     137
11     202
12     170
13     446
14      29
15      39
16      44
17     253
18      17
19      34
20      18
21      37
22     147
23      12
24      31
25      15
26     117
27       8
28      38
29      23
30     198
31      29
32     122
33      50
34      60
35     357
36     329
37     457
38     609
39    4744
40    1120
41     591
42     328
43     148
44      46
45      10
46       1
47       1
48       7
50       2
Name: prglngth, dtype: int64

Q3: Create a new column named totalwgt_kg that contains birth weight in kilograms. 
Compute its mean. 
Remember that when you create a new column, you have to use dictionary syntax, not dot notation.

In [31]:
preg["totalwgt_kg"] = preg.totalwgt_lb / 2.2
preg.totalwgt_kg.mean()

0        4.005682
1        3.579545
2        4.147727
3        3.181818
4        2.812500
           ...   
13588    2.812500
13589         NaN
13590         NaN
13591    3.409091
13592    3.409091
Name: totalwgt_kg, Length: 13593, dtype: float64

Q4: Select the age_r column from resp and print the value counts. How old are the youngest and oldest respondents?

In [15]:
resp = nsfg.ReadFemResp()
resp.head

<bound method NDFrame.head of       caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
0       2298        1         5         5            1          5.0     27   
1       5012        1         5         1            5          5.0     42   
2      11586        1         5         1            5          5.0     43   
3       6794        5         5         4            1          5.0     15   
4        616        1         5         4            1          5.0     20   
...      ...      ...       ...       ...          ...          ...    ...   
7638   11018        1         5         2            5          3.0     34   
7639    6075        5         5         3            5          3.0     17   
7640    5649        1         5         2            5          5.0     29   
7641     501        5         5         3            5          2.0     16   
7642   10252        1         5         2            5          2.0     28   

      age_r  cmbirth  agescrn  ..

In [34]:
resp.age_r.value_counts().sort_index()

15    217
16    223
17    234
18    235
19    241
20    258
21    267
22    287
23    282
24    269
25    267
26    260
27    255
28    252
29    262
30    292
31    278
32    273
33    257
34    255
35    262
36    266
37    271
38    256
39    215
40    256
41    250
42    215
43    253
44    235
Name: age_r, dtype: int64

Ans: The youngest responden is 15 years old, and oldest respondent is 44 years old.  

Q5: How old is the respondent with caseid 1?

In [20]:
resp[resp.caseid == 1].age_r

1069    44
Name: age_r, dtype: int64

Ans: 44 years old.

Q6: What are the pregnancy lengths for the respondent with caseid 2298?

In [27]:
preg[preg.caseid == 2298].prglngth

2610    40
2611    36
2612    30
2613    40
Name: prglngth, dtype: int64

Ans: Above data shows case id 2298's pregnancy lengths of 4 times pregenancy.

Q7: What was the birthweight of the first baby born to the respondent with caseid 5012?

In [25]:
preg[preg.caseid == 5012].birthwgt_lb

5515    6.0
Name: birthwgt_lb, dtype: float64

Ans: 6.0 pounds.

# Exercise 1.2

In the repository you downloaded, you should find a file named chap01ex.py; using this file as a starting place, write a function that reads the respondent file, 2002FemResp.dat.gz.

In [42]:
from __future__ import print_function, division

import numpy as np
import sys

import thinkstats2

def ReadFemResp(dct_file="2002FemResp.dct",
                dat_file="2002FemResp.dat.gz"):
    """Reads the NSFG respondent data.

    returns: DataFrame
    """
    dct = thinkstats2.ReadStataDct(dct_file)
    df = dct.ReadFixedWidth(dat_file, compression="gzip")
    return df

resp = ReadFemResp()
resp.head()


caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
0    2298        1         5         5            1          5.0     27   
1    5012        1         5         1            5          5.0     42   
2   11586        1         5         1            5          5.0     43   
3    6794        5         5         4            1          5.0     15   
4     616        1         5         4            1          5.0     20   

   age_r  cmbirth  agescrn  ...  pubassis_i      basewgt  adj_mod_basewgt  \
0     27      902       27  ...           0  3247.916977      5123.759559   
1     42      718       42  ...           0  2335.279149      2846.799490   
2     43      708       43  ...           0  2335.279149      2846.799490   
3     15     1042       15  ...           0  3783.152221      5071.464231   
4     20      991       20  ...           0  5341.329968      6437.335772   

      finalwgt  secu_r  sest  cmintvw  cmlstyr  screentime   intvlngth  
0  5556.717241       2    18     1234     1222    18:26:36  110.492667  
1  4744.191350       2    18     1233     1221    16:30:59   64.294000  
2  4744.191350       2    18     1234     1222    18:19:09   75.149167  
3  5923.977368       2    18     1234     1222    15:54:43   28.642833  
4  7229.128072       2    18     1233     1221    14:19:44   69.502667  

[5 rows x 3087 columns]

The variable pregnum is a recode that indicates how many times each re- spondent has been pregnant. Print the value counts for this variable and compare them to the published results in the NSFG codebook.
You can also cross-validate the respondent and pregnancy files by comparing pregnum for each respondent with the number of records in the pregnancy file.
You can use nsfg.MakePregMap to make a dictionary that maps from each caseid to a list of indices into the pregnancy DataFrame.

In [70]:
resp.pregnum

0       4
1       1
2       1
3       0
4       0
       ..
7638    1
7639    0
7640    0
7641    0
7642    0
Name: pregnum, Length: 7643, dtype: int64

In [41]:
resp.pregnum.value_counts().sort_index()

0     2610
1     1267
2     1432
3     1110
4      611
5      305
6      150
7       80
8       40
9       21
10       9
11       3
12       2
14       2
19       1
Name: pregnum, dtype: int64

In [84]:
import nsfg
from pprint import pprint

def addOneInDict(d, val):
    if val not in d:
        d[val] = 1
    else:
        d[val] += 1

def main():
    preg = nsfg.ReadFemPreg()
    preg_map = nsfg.MakePregMap(preg)
    fem_preg_dict = {}
    
    for key, value in preg_map.items():
        preg_num = len(value)
        addOneInDict(fem_preg_dict, preg_num)

    pprint(fem_preg_dict)

if __name__ == '__main__':
    main()

{1: 1267,
 2: 1432,
 3: 1110,
 4: 611,
 5: 305,
 6: 150,
 7: 80,
 8: 40,
 9: 21,
 10: 9,
 11: 3,
 12: 2,
 14: 2,
 19: 1}


Thus, we can see that comparing pregnum for each respondent with the number of records in the respondent file(2002FemResp) and pregnancy file(FemPreg) are same.

# Exercise 1.3

Think about questions you find personally interesting, or items of conven- tional wisdom, or controversial topics, or questions that have political conse- quences, and see if you can formulate a question that lends itself to statistical inquiry.

Ans: I am interested in a question of "Do international students major in Computer Science in United States have higher job-placement rate than other majors after graduated?".